import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { IBM_Plex_Sans } from 'next/font/google'

const ibm = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: '400',
})

import './globals.css'
import ThemeProvider from './providers'

export const metadata: Metadata = {
  title: 'Jobify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='fr' suppressHydrationWarning>
        <body className={ibm.className}>
          <ThemeProvider>{children}</ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
